# Generated by Django 3.0.6 on 2020-05-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcrud', '0002_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
